import type { Alert, AlertSeverity, AlertStatus, AlertStatusEvent, Platform } from "@/types";
import { MINUTE_MS, at, bucketEndMs } from "./scenario";
import { bucketTotal } from "./aggregate";
import { TOPIC_SPECS } from "./topics";
import { compositeScore, computeConfidence, evaluateSignals, type EvalContext } from "./signals";
import { trendIdOf } from "./trends-ids";

/**
 * Simulated alert store. Alerts are generated by evaluating the same six
 * signals as the trends, at the hour in which the alert was raised. An alert is
 * raised when at least 3 of the 6 signals fire.
 */

interface AlertDef {
  id: string;
  topicId: string;
  /** Bucket whose completion triggered the alert */
  bucket: number;
  status: AlertStatus;
  history: AlertStatusEvent[];
}

const DEFS: AlertDef[] = [
  {
    id: "ALR-2026-0144",
    topicId: "t-railway",
    bucket: 44,
    status: "new",
    history: [],
  },
  {
    id: "ALR-2026-0143",
    topicId: "t-monsoon",
    bucket: 46,
    status: "investigating",
    history: [
      {
        ts: at(13, 40),
        status: "investigating",
        note: "Picked up for review; checking whether flooding reports overlap with the rail disruption.",
        actor: "analyst",
      },
    ],
  },
  {
    id: "ALR-2026-0138",
    topicId: "t-metro",
    bucket: 14,
    status: "resolved",
    history: [
      {
        ts: at(5, 40, 1),
        status: "investigating",
        note: "Reviewing the negative spike after the fare-slab announcement.",
        actor: "analyst",
      },
      {
        ts: at(9, 30, 1),
        status: "resolved",
        note: "Volume and negative share are back near baseline; no further action needed.",
        actor: "analyst",
      },
    ],
  },
];

export function severityFor(score: number, mentionsPerHour: number): AlertSeverity {
  if (score >= 0.85 && mentionsPerHour >= 500) return "critical";
  if (score >= 0.8) return "high";
  if (score >= 0.4) return "medium";
  return "low";
}

const listJoin = (items: string[]): string =>
  items.length <= 1 ? (items[0] ?? "") : `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;

export function buildAlerts(ctx: EvalContext): Alert[] {
  const alerts: Alert[] = DEFS.map((def) => {
    const spec = TOPIC_SPECS.find((s) => s.id === def.topicId);
    if (!spec) throw new Error(`Unknown topic for alert ${def.id}`);
    const h = ctx.hourly[def.topicId];
    const evidence = evaluateSignals(ctx, def.topicId, def.bucket);
    const fired = evidence.filter((s) => s.fired);
    const score = compositeScore(evidence);
    const atAlert = bucketTotal(h[def.bucket]);
    const createdAt = new Date(bucketEndMs(def.bucket) + 5 * MINUTE_MS).toISOString();

    let x = 0;
    let tg = 0;
    for (let i = Math.max(0, def.bucket - 2); i <= def.bucket; i++) {
      x += bucketTotal(h[i], "x");
      tg += bucketTotal(h[i], "telegram");
    }
    const platforms: Platform[] = [];
    if (x / Math.max(1, x + tg) >= 0.05) platforms.push("x");
    if (tg / Math.max(1, x + tg) >= 0.05) platforms.push("telegram");

    const history: AlertStatusEvent[] = [
      {
        ts: createdAt,
        status: "new",
        note: `Alert generated automatically: ${fired.length} of ${evidence.length} signals fired.`,
        actor: "system",
      },
      ...def.history,
    ];

    return {
      id: def.id,
      topicId: def.topicId,
      topicName: spec.name,
      trendId: trendIdOf(def.topicId),
      severity: severityFor(score, atAlert),
      status: def.status,
      createdAt,
      updatedAt: history[history.length - 1].ts,
      confidence: computeConfidence(ctx, def.topicId, def.bucket, evidence),
      score,
      platforms,
      triggerReason: `${fired.length} of ${evidence.length} signals fired: ${listJoin(fired.map((s) => s.label.toLowerCase()))}.`,
      whyBullets: fired.map((s) => s.explanation),
      evidence,
      mentionsPerHourAtAlert: atAlert,
      mentionsPerHourNow: bucketTotal(h[h.length - 1]),
      history,
    };
  });

  for (const a of alerts) {
    if (a.evidence.filter((s) => s.fired).length < 3) {
      throw new Error(`Alert ${a.id} would not meet the "3 of 6 signals" rule`);
    }
  }
  return alerts.sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt));
}
